// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("ActivityListCtrl", [
  '$scope', 'Activity', 'Restangular', function($scope, Activity, Restangular) {
    var activities;
    Restangular.setBaseUrl('http://127.0.0.1:6008');
    Restangular.setRequestSuffix('.json');
    activities = Restangular.all('activities');
    $scope.activityList = activities.getList().$object;
    $scope.spy = function(item) {
      console.log(item);
      return alert('superwolf');
    };
    $scope["delete"] = function(item) {
      return item.remove().then(function() {
        return $scope.activityList.remove(function(activity) {
          return activity.id === item.id;
        });
      });
    };
    $scope.deleteByIndex = function(index) {};
    return $scope.show = function() {
      alert('superwolf');
      return console.log($scope.activityList.length);
    };
  }
]);

angular.module("MobileCMSApp").filter("activityPublishedTranslate", function() {
  return function(input) {
    if (input) {
      return "是";
    } else {
      return "否";
    }
  };
});

angular.module("MobileCMSApp").filter("activityTypeTranslate", function() {
  var map;
  map = ["无", "游客", "注册", "电话", "激活"];
  return function(input) {
    return map[input];
  };
});

angular.module("MobileCMSApp").filter("activityStatusTranslate", function() {
  var map;
  map = ["关闭", "打开"];
  return function(input) {
    return map[input];
  };
});

angular.module("MobileCMSApp").filter("activityPublishedTranslate", function() {
  return function(input) {
    if (input) {
      return "是";
    } else {
      return "否";
    }
  };
});
