// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module("MobileCMSApp").controller("ActivityEditCtrl", [
    '$scope', '$stateParams', 'MobileService', '$location', function($scope, $stateParams, MobileService, $location) {
      $scope.activity = MobileService.one('activities', $stateParams.id).get().$object;
      $scope.submit = function() {
        var body;
        body = {
          Activity: $scope.activity
        };
        return $scope.activity.customPUT(body).then(function(activity) {
          history.back();
          return scope.$apply();
        }, function() {
          console.log('update error');
          return console.log(arguments);
        });
      };
      return $scope["delete"] = function() {
        return $scope.activity.remove().then(function(activity) {
          history.back();
          return scope.$apply();
        }, function() {
          console.log('delete error');
          return console.log(arguments);
        });
      };
    }
  ]);

}).call(this);
