// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("ActivityEditCtrl", [
  '$scope', 'Activity', function($scope, Activity) {
    $scope.awesomeThings = ["HTML5 Boilerplate", "AngularJS", "Karma"];
    $scope.activity = Activity.get({
      id: 97
    });
    return $scope.showValues = (function(_this) {
      return function() {
        return console.log($scope.activity);
      };
    })(this);
  }
]);
