// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("ActivityCreateCtrl", [
  '$scope', 'Activity', 'Restangular', '$location', function($scope, Activity, Restangular, $location) {
    Restangular.setBaseUrl('http://127.0.0.1:6008');
    Restangular.setRequestSuffix('.json');
    $scope.activity = {
      type: 1,
      order: 100,
      status: 1,
      published: false
    };
    return $scope.submit = function() {
      var body;
      body = {
        Activity: $scope.activity
      };
      return Restangular.all('activities').post(body).then(function(activity) {
        return $location.path('/activity');
      });
    };
  }
]);
