// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("ActivityCtrl", [
  '$scope', 'Activity', function($scope, Activity) {
    $scope.awesomeThings = ["HTML5 Boilerplate", "AngularJS", "Karma"];
    $scope.activity = {
      title: "今晚打老虎",
      type: 1,
      status: 1,
      published: 1,
      order: 0,
      radio: "middle"
    };
    return $scope.showValues = (function(_this) {
      return function() {
        return console.log($scope.activity);
      };
    })(this);
  }
]);
