// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("ActivityListCtrl", [
  '$scope', 'MobileService', '$state', function($scope, MobileService, $state) {
    var activities, activitiesList;
    activities = MobileService.all('activities');
    activitiesList = activities.getList();
    $scope.activityList = activitiesList.$object;
    $scope["delete"] = function(item) {
      return item.remove().then(function() {
        return $scope.activityList = _.without($scope.activityList, item);
      });
    };
    return $scope.gotoEdit = function(activityId) {
      return $state.go('^.edit', {
        id: activityId
      });
    };
  }
]);

angular.module("MobileCMSApp").filter("activityPublishedTranslate", function() {
  return function(input) {
    if (input) {
      return "是";
    } else {
      return "否";
    }
  };
});

angular.module("MobileCMSApp").filter("activityTypeTranslate", function() {
  var map;
  map = ["无", "游客", "注册", "电话", "激活"];
  return function(input) {
    return map[input];
  };
});

angular.module("MobileCMSApp").filter("activityStatusTranslate", function() {
  var map;
  map = ["关闭", "打开"];
  return function(input) {
    return map[input];
  };
});

angular.module("MobileCMSApp").filter("activityPublishedTranslate", function() {
  return function(input) {
    if (input) {
      return "是";
    } else {
      return "否";
    }
  };
});
