// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("ActivityCreateCtrl", [
  '$scope', 'Activity', 'Restangular', function($scope, Activity, Restangular) {
    Restangular.setBaseUrl('http://127.0.0.1:6008');
    Restangular.setRequestSuffix('.json');
    $scope.awesomeThings = ["HTML5 Boilerplate", "AngularJS", "Karma"];
    $scope.activity = {
      status: 0,
      type: 1
    };
    $scope.create = function() {
      return console.log($scope.activity);
    };
    console.log('activity create');
    return $scope.showValues = (function(_this) {
      return function() {
        return console.log($scope.activity);
      };
    })(this);
  }
]);
