// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module("MobileCMSApp").controller("ActivityCreateCtrl", [
    '$scope', 'MobileService', '$location', function($scope, MobileService, $location) {
      $scope.activity = {
        type: 1,
        order: 100,
        status: 1,
        published: false
      };
      return $scope.submit = function() {
        var body;
        body = {
          Activity: $scope.activity
        };
        return MobileService.all('activities').post(body).then(function(activity) {
          history.back();
          return scope.$apply();
        }, function() {
          console.log('create error');
          return console.log(arguments);
        });
      };
    }
  ]);

}).call(this);
