// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("BulletinNewCtrl", [
  '$scope', 'MobileService', '$stateParams', function($scope, MobileService, $stateParams) {
    var _ref;
    $scope.bulletin = {
      type: 0,
      userType: (_ref = $stateParams.userType) != null ? _ref : 0
    };
    return $scope.submit = function() {
      var body;
      body = {
        Bulletin: $scope.bulletin
      };
      return MobileService.all('bulletins').post(body).then(function(bulletin) {
        history.back();
        return scope.$apply();
      }, function() {
        console.log('create error');
        return console.log(arguments);
      });
    };
  }
]);
