// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("BulletinListCtrl", [
  '$scope', 'MobileService', '$state', function($scope, MobileService, $state) {
    var bulletins;
    $scope.categoryList = [
      {
        filter: {
          userType: 0
        },
        type: "游客"
      }, {
        filter: {
          userType: 1
        },
        type: "注册用户"
      }, {
        filter: {
          userType: 3
        },
        type: "激活客户"
      }
    ];
    bulletins = MobileService.all('bulletins').getList();
    $scope.bulletinList = bulletins.$object;
    return bulletins.then(function() {
      return $scope.activeBulletinList = _.chain($scope.bulletinList).reject({
        "userType": null
      }).groupBy('userType').map(function(list) {
        return _.max(list, 'id');
      }).value();
    });
  }
]);

angular.module("MobileCMSApp").filter("bulletinTypeTranslate", function() {
  var map;
  map = ["不显示", "聊天", "活动", "资讯"];
  return function(input) {
    return map[input];
  };
});

angular.module("MobileCMSApp").filter("bulletinUserTypeTranslate", function() {
  var map;
  map = ["游客", "注册用户", "", "激活客户"];
  return function(input) {
    return map[input];
  };
});

angular.module("MobileCMSApp").filter("bulletinActiveFilter", function() {
  return function(array, input) {
    return true;
  };
});
