// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module("MobileCMSApp").controller("ChannelListCtrl", [
    '$scope', 'Restangular', '$state', function($scope, MobileService, $state) {
      var channels;
      channels = MobileService.all('channels');
      return $scope.channelList = channels.getList().$object;
    }
  ]);

}).call(this);
