// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("ChannelListCtrl", [
  '$scope', 'Restangular', '$state', function($scope, MobileService, $state) {
    var channelList, channels;
    channels = MobileService.all('channels');
    channelList = channels.getList();
    return $scope.channelList = channelList.$object;
  }
]);
