// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("LoginCtrl", [
  '$scope', 'ServerCurrent', 'Restangular', '$state', function($scope, ServerCurrent, Restangular, $state) {
    Restangular.setBaseUrl(ServerCurrent.channel_server);
    Restangular.setRequestSuffix('');
    $scope.userinfo = {};
    return $scope.submit = function() {
      return Restangular.all('login').post("username=admin&password=wangsisi").then(function() {
        return console.log(arguments);
      });
    };
  }
]);
