// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module("MobileCMSApp").controller("LoginCtrl", [
    '$scope', 'MobileService', '$state', function($scope, MobileService, $state) {
      $scope.userinfo = {};
      return $scope.submit = function() {
        return MobileService.all('login').post($scope.userinfo).then(function() {
          return console.log(arguments);
        });
      };
    }
  ]);

}).call(this);
