// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("MainCtrl", [
  '$scope', 'Activity', function($scope, Activity) {
    console.log(Activity.query());
    $scope.awesomeThings = ["HTML5 Boilerplate", "AngularJS", "Karma"];
    return $scope.button = {
      toggle: false,
      checkbox: {
        left: false,
        middle: true,
        right: false
      },
      radio: "left"
    };
  }
]);
