// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("MainCtrl", [
  '$scope', 'Activity', function($scope, Activity) {
    $scope.awesomeThings = ["HTML5 Boilerplate", "AngularJS", "Karma"];
    $scope.activity = {
      type: 1,
      status: {
        1: true
      }
    };
    return $scope.show = function() {
      return console.log($scope.activity);
    };
  }
]);
