// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").controller("MainCtrl", [
  '$scope', 'Activity', function($scope, Activity) {
    $scope.activities = Activity.query();
    $scope.awesomeThings = ["HTML5 Boilerplate", "AngularJS", "Karma"];
    $scope.button = {
      toggle: false,
      checkbox: {
        left: false,
        middle: true,
        right: false
      },
      radio: "middle"
    };
    return $scope.showValues = (function(_this) {
      return function() {
        return console.log($scope.button);
      };
    })(this);
  }
]);
