// Generated by CoffeeScript 1.7.1
console.log('superwolf');

angular.module("ActivityService", ["ngResource"]).factory('Activity', [
  '$resource', function($resource) {
    return $resource('http://127.0.0.1\\:6008/activities.json', {}, {
      query: {
        method: 'GET',
        params: {},
        isArray: true
      }
    });
  }
]);
