// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("MobileCMSApp").factory("MobileService", [
  'Restangular', 'ServerCurrent', '$state', function(Restangular, ServerCurrent, $state) {
    Restangular.setBaseUrl(ServerCurrent.channel_server);
    Restangular.setRequestSuffix('.json');
    Restangular.setErrorInterceptor(function(error) {
      console.log(error);
      if (error.status === 403) {
        return window.location = window.location.origin + "/login.html";
      }
    });
    Restangular.setDefaultHttpFields({
      withCredentials: true
    });
    return Restangular;
  }
]);
