// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module("MobileCMSApp").factory("MobileService", [
    'Restangular', 'ServerCurrent', function(Restangular, ServerCurrent) {
      Restangular.setBaseUrl(ServerCurrent.channel_server);
      Restangular.setRequestSuffix('.json');
      return Restangular;
    }
  ]);

}).call(this);
