// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('common.server.current', ['common.server.list', 'common.env']).factory('ServerCurrent', [
    'ServerList', 'Env', function(ServerList, Env) {
      return ServerList[Env.agent][Env.env];
    }
  ]);

}).call(this);
