// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("MobileCMSApp").directive('backButton', function() {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {
        var goBack;
        goBack = function() {
          history.back();
          return scope.$apply();
        };
        return element.bind('click', goBack);
      }
    };
  });

}).call(this);
